# -*- coding: utf-8 -*-
# Form implementation generated from reading ui file 'jarvis3.ui'
# Created by: PyQt5 UI code generator 5.15.11 
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(756, 612)
        MainWindow.setStyleSheet("background-color: #121212; /* Dark theme */\n"
"color: #00ffff; /* Neon text */")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.speakbutton = QtWidgets.QPushButton(self.centralwidget)
        self.speakbutton.setGeometry(QtCore.QRect(310, 400, 91, 81))
        self.speakbutton.setStyleSheet("QPushButton {\n"
"    background-color: #222;  /* Dark background */\n"
"    color: #00ffff;  /* Neon cyan text */\n"
"    border-radius: 30px;  /* Circular button */\n"
"    font-size: 18px;\n"
"    padding: 10px;\n"
"    border: 2px solid #00ffff; /* Neon border */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #00ffff;\n"
"    color: #222;\n"
"}")
        self.speakbutton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../Users/Asus/Downloads/mic.jpeg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)  
        self.speakbutton.setIcon(icon)
        self.speakbutton.setIconSize(QtCore.QSize(70, 70))
        self.speakbutton.setObjectName("speakbutton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(140, 110, 481, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: #00ffff;  /* Neon cyan text */\n"
"background-color: #222;  /* Dark background */\n"
"font-size: 18px;\n"
"font-weight: bold;\n"
"\n"
"padding: 10px;\n"
"border-radius: 10px;\n"
"")
        self.label.setObjectName("label")
        # self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        # self.progressBar.setGeometry(QtCore.QRect(20, 560, 118, 23))
        # self.progressBar.setStyleSheet("QProgressBar {\n"
# "    background-color: #222; /* Dark background */\n"
# "    color: #00ffff; /* Neon cyan text */\n"
# "    border-radius: 10px;\n"
# "    text-align: center;\n"
# "    font-size: 16px;\n"
# "    font-weight: bold;\n"
# "}\n"
# "\n"
# "QProgressBar::chunk {\n"
# "    background-color: #00ffff; /* Neon effect */\n"
# "    width: 10px;\n"
# "    margin: 1px;\n"
# "    border-radius: 5px;\n"
# "}")
        # self.progressBar.setProperty("value",24)
        # self.progressBar.setObjectName("progressBar")
        self.wavelabel = QtWidgets.QLabel(self.centralwidget)
        self.wavelabel.setGeometry(QtCore.QRect(140, 200, 471, 161))
        self.wavelabel.setStyleSheet("QLabel {\n"
"    color: #00ffff;  /* Neon cyan text */\n"
"    font-size: 22px;\n"
"    font-weight: bold;\n"
"    border: 2px solid #00ffff;  /* Neon border */\n"
"    padding: 10px;\n"
"    border-radius: 10px;\n"
"}")
        self.wavelabel.setText("")
        self.wavelabel.setObjectName("wavelabel")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "                   How  can I  assist  you?"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
